export const GROUP_COLORS = {
  Sea: '#0ea5e9',
  Sunset: '#f97316',
  FireShow : '#f43f5e',
  Adventure: '#10b981',
  Snorkel: '#3b82f6',
  Viewpoint: '#8b5cf6',
};

export const SPECIAL_TAGS = ['Solo', 'Peace', 'Couple', 'Family', 'Friendly'];

export const LOCATIONS = [
  {
    id: 'ao-nang',
    name: 'Ao Nang Beach',
    group: 'Sea',
    tags: ['Family', 'Pier Access', 'Easy Walk','FireShow'],
    recommended: false,
    score: undefined,
    coordinates: [8.0404, 98.8222],
    highlightTag: 'Starting Point',
    shortDescription: 'Main beach and pier for most JoinJoy trips.',
  },
  {
    id: 'railay',
    name: 'Railay Beach',
    group: 'Adventure',
    tags: ['Romantic', 'Easy Walk', 'Clear Water'],
    recommended: false,
    score: undefined,
    coordinates: [8.0117, 98.8395],
    highlightTag: 'Cliff & Sunset',
    shortDescription: 'Famous cliffs, sunset views, and chill beach vibes.',
  },
  {
    id: 'phi-phi',
    name: 'Phi Phi Islands',
    group: 'Sea',
    tags: ['Clear Water', 'Family'],
    recommended: false,
    score: undefined,
    coordinates: [7.7407, 98.7765],
    highlightTag: 'Island Hopping',
    shortDescription: 'Iconic islands with turquoise water and snorkeling.',
  },
  {
    id: 'hong',
    name: 'Hong Island',
    group: 'Snorkel',
    tags: ['Clear Water', 'Family', 'Calm Lagoon'],
    recommended: false,
    score: undefined,
    coordinates: [8.1089, 98.7021],
    highlightTag: 'Lagoon',
    shortDescription: 'Stunning lagoon with calm water and kayaking.',
  },
  {
    id: 'thale-waek',
    name: 'Thale Waek',
    group: 'Adventure',
    tags: ['Sandbar', 'Clear Water'],
    recommended: false,
    score: undefined,
    coordinates: [7.99, 98.8144],
    highlightTag: 'Sandbar',
    shortDescription: 'Famous sandbar that appears at low tide.',
  },
  {
    id: 'ao-nang-sunset',
    name: 'Ao Nang Beach Fire Show',
    group: 'Fire Show',
    tags: ['Show', 'Family', 'Easy Walk'],
    recommended: false,
    score: undefined,
    coordinates: [8.031669881889947, 98.8216320402158],
    highlightTag: 'Sunset Point',
    shortDescription: 'Beachfront sunset with nightly fire shows and music.',
  },
  {
    id: 'nopparat-sunset',
    name: 'Nopparat Thara Beach Sunset',
    group: 'Sunset',
    tags: ['Family', 'Easy Walk'],
    recommended: false,
    score: undefined,
    coordinates: [8.042996646771988, 98.80915062374889],
    highlightTag: 'Sunset Point',
    shortDescription: 'Quiet sunset spot near the Landmark night market.',
  },
  {
    id: 'railay-west-sunset',
    name: 'Railay West Sunset',
    group: 'Sunset',
    tags: ['Romantic', 'Clear Water', 'Family'],
    recommended: true,
    score: 94,
    coordinates: [8.011867631403003, 98.83779902910392],
    highlightTag: 'Sunset Point',
    shortDescription: 'Magical sunsets surrounded by dramatic limestone cliffs.',
  },
  {
    id: 'din-daeng-doi',
    name: 'Din Daeng Doi Viewpoint',
    group: 'Viewpoint',
    tags: ['Hike', 'Panoramic'],
    recommended: false,
    score: undefined,
    coordinates: [8.110198323318548, 98.78414908067876],
    highlightTag: 'Viewpoint',
    shortDescription: 'Hilltop viewpoint offering sunrise, sunset, and sea-fog scenes.',
  },
  {
    id: 'klong-muang-beach',
    name: 'Klong Muang Beach Sunset',
    group: 'Sunset',
    tags: ['Romantic', 'Calm Waves'],
    recommended: false,
    score: undefined,
    coordinates: [8.055302121766385, 98.75930705734284],
    highlightTag: 'Sunset Point',
    shortDescription: 'Peaceful beach with calm waves and a relaxed sunset atmosphere.',
  },
  {
    id: 'tub-kaek-sunset',
    name: 'Tub Kaek Beach Sunset',
    group: 'Sunset',
    tags: ['Romantic', 'Family'],
    recommended: false,
    score: undefined,
    coordinates: [8.091723042677, 98.74713314218624],
    highlightTag: 'Sunset Point',
    shortDescription: 'Sunset view facing the Hong Islands in a serene setting.',
  },
  {
    id: 'khao-thong-hill',
    name: 'Khao Thong Hill Café',
    group: 'Viewpoint',
    tags: ['View Café', 'Easy Walk'],
    recommended: false,
    score: undefined,
    coordinates: [8.172984889255703, 98.75259315296445],
    highlightTag: 'Viewpoint Café',
    shortDescription: 'Panoramic sunset viewpoint overlooking Hong Islands with café.',
  },
  {
    id: 'buffalo-nose-cape',
    name: 'Buffalo Nose Cape',
    group: 'Adventure',
    tags: ['Hike', 'Remote'],
    recommended: false,
    score: undefined,
    coordinates: [8.136152250559762, 98.7355327106346],
    highlightTag: 'Adventure Spot',
    shortDescription: 'Dramatic natural stone arches with a remote, scenic sunset view.',
  },
];

export const GROUPS = ['All', ...new Set(LOCATIONS.map((location) => location.group))];
